name: Terraform

on:
  push:
    branches:
      - master
    paths:
      - 'pro-project/github-oidc/**'
      - 'backend/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:

  github-oidc:
    name: Deploy github-oidc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pro-project/github-oidc

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::136518012363:role/pro-project-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=bucket=${{ secrets.TF_BACKEND_BUCKET }} -backend-config=key=pro-project/terraform.tfstate -backend-config=region=${{ env.AWS_REGION }} -backend-config=encrypt=true

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=variables/pro_project.tfvars


  backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::136518012363:role/pro-project-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config=bucket=${{ secrets.TF_BACKEND_BUCKET }} -backend-config=key=backend/terraform.tfstate -backend-config=region=${{ env.AWS_REGION }} -backend-config=encrypt=true

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=variables/backend.tfvars