name: Terraform

on:
  push:
    branches:
      - master
    paths:
      - 'pro-project/github-oidc/**'
      - 'backend/**'
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_BACKEND_KEY: pro-project/terraform.tfstate

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - folder: pro-project/github-oidc
            backend_key: pro-project/terraform.tfstate
            var_file: variables/pro_project.tfvars

          - folder: backend
            backend_key: backend/terraform.tfstate
            var_file: variables/pro_project.tfvars

    defaults:
      run:
        working-directory: ./${{ matrix.folder }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::136518012363:role/pro-project-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
            -backend-config="key=${{ matrix.backend_key }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true" \
            -backend-config="use_lockfile=true"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=${{ matrix.var_file }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -var-file=${{ matrix.var_file }}
